# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1bff66861df169fea41787373b88db5d96151321d9e216daf469136d274cafa890cdb49e2f0eaa5126255e3f4d0fa957a36cd25e294a95de62a6ce34025f4ea

test:
  secret_key_base: 66f17689df0cfb606be05cb73cfd7ef347250080e9d4c34de9ff97dcad4115a9f5a958de0027d87072366aa55c34a30d8004a169f9829434f043e7044ebdaff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
